services:
  - type: web
    name: carebridge
    env: php
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: carebridge
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: ""
